[package]
name = "ritmo_db"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { workspace = true }
ritmo_errors = { path = "../ritmo_errors" }
ritmo_core = { path = "../ritmo_core" }
chrono = "0.4.41"

[dev-dependencies]
tempfile = "3.20.0"
